import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import SidebarNav from "@/components/SidebarNav";
import HeaderNav from "@/components/HeaderNav";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Psiu Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-[#FAFAFA] text-black flex overflow-hidden", // Adicionando overflow-hidden
          inter.className,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        <Toaster />
        <aside className="hidden min-h-screen bg-[#F7F8FA] md:block border-r md:w-[80px] transition-all duration-300">
          <SidebarNav />
        </aside>
        <main className="flex-1 overflow-y-auto">
          {" "}
          {/* Permitir rolagem vertical no main */}
          <HeaderNav />
          <div className="p-2 md:p-5 flex flex-col gap-5 w-full h-full overflow-auto">
            {" "}
            {/* Permitir rolagem dentro do main */}
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
